version: "3.8"

services:
  postgres:
    image: postgis/postgis:latest
    env_file:
      - .env
    volumes:
      - ./postgresql/dumps:/code/dumps
      - ./postgresql/data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
